import "~/styles/globals.css";
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { AuthProvider } from "./_components/providers/session-provider";

export const metadata: Metadata = {
  title: "Qala Coffee App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/icons/logo.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <AuthProvider>
            {children}
          </AuthProvider> 
        </TRPCReactProvider>
      </body>
    </html>
  );
}
